### ISSUE TITLE
Bug: Lives and separator over laps 

### ISSUE THREAD

**Issue by darewealth** [sanjeev309/storklight#7]
### Describe the Bug:
When I played, and get 10 lives, the love live indicator overlaps the 's' of the score. And, did you create the game to have a maximum of 10 lives? Also, the vertical separator of score and time get overlapped when the user gets above 100 scores.

### To Reproduce:
* Launch the app

* Play and make sure you have up to 10 lives. 

* And try to also score above 100 to see the second behavior. 

### Expected Behavior:
I expect that the lives and the vertical line separator shouldn't get overlapped by anything. I think this is a bug that need a fix.   

### Screenshot Of The Bug
![IMG_20190503_081749](https://user-images.githubusercontent.com/36304257/57124131-705c9a00-6d7c-11e9-9f68-86fd3231addd.jpg)

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [0.0.5]

**Comment by sanjeev309** [comment]
Hi @darewealth , Thanks for the bug report. I have accidentally pushed an update with 10 lives by default. The game will start with 3 lives from next update.

Anyway, There is an upper limit of 10 lives simply because of the issue with lives and score overlapping. I have tested on different devices but seems like 10 is not an optimal number. Maybe 8 will do? Other than that, is the game appealing with a limit on number of lives? 

Or else I will be implementing the same method that super mario did :  ♥ x 10 . Seems good? With this fix, we can shift score to the left fixing overlap with time : )

Other than that, What is your take on the game sounds that have been added? Do they blend with the overall environment? Is there anything inconvenient in the game sound that you feel?

**Comment by sanjeev309** [comment]
Hi @darewealth ,

I actually went ahead and implemented the multiplier system for lives. Here is a screenshot for the same. Do let me know if this looks decent now. : )

![](https://imgur.com/LGol3H9.png)

Also, game will start with 5 lives, not 3. Just a minor fact correction from my last comment.

**Comment by darewealth** [comment]
Hi,

>is the game appealing with a limit on number of lives?

I think the number is ok, and I find it appealing since it is even not that easy to attain.

>♥ x 10 . Seems good?

That seems very good.

I can't say anything about the sound for now, but there are things to improve on the game. I will write a couple of suggestion, and submit soon.


![image](https://user-images.githubusercontent.com/36304257/57278564-b4aea980-709e-11e9-97a0-73d160eae2cd.png)


This looks nice, and perfect.

**Comment by sanjeev309** [comment]
> I will write a couple of suggestion, and submit soon.

Sure, Please feel free to do so. Thank you : )

--------------------------------------------------------------
Commit 2e2e3a0 resolves this issue.
Scheduled for next release.
